
imports:
    - { resource: config.ini }

services:
    sitebuilder_filesystem:
        class: Inanimatt\SiteBuilder\TransformingFilesystem
        arguments: [@event_dispatcher]

    frontmatter_transformer:
        class: Inanimatt\SiteBuilder\Transformer\FrontmatterTransformer
        arguments: [@frontmatter_reader]
        tags:
            - { name: sitebuilder.transformer, priority: 255 }

    twig_markdown_transformer:
        class: Inanimatt\SiteBuilder\Transformer\TwigMarkdownTransformer
        arguments: [@markdown, @twig, %default_template%]
        tags:
            - { name: sitebuilder.transformer, priority: 127 }

    twig_html_transformer:
        class: Inanimatt\SiteBuilder\Transformer\TwigHtmlTransformer
        arguments: [@twig, %default_template%]
        tags:
            - { name: sitebuilder.transformer, priority: 127 }

    scss_transformer:
        class: Inanimatt\SiteBuilder\Transformer\SassTransformer
        arguments: [@sass_process_builder]
        tags:
            - { name: sitebuilder.transformer, priority: 127 }

    sass_process_builder:
        class: Inanimatt\SiteBuilder\Transformer\SassProcessBuilder
        arguments: [%sass_path%, 'compressed']

    event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher

    frontmatter_reader:
        class: Inanimatt\SiteBuilder\FrontmatterReader
        arguments: [@yaml]

    twig.loader:
        class: Twig_Loader_Filesystem
        arguments: [%template_path%]

    twig:
        class: Twig_Environment
        arguments: [@twig.loader]

    yaml:
        class: Symfony\Component\Yaml\Parser

    markdown:
        class: dflydev\markdown\MarkdownExtraParser
